language: php
php:
  - 5.2
  - 5.3
  - 5.4
  - 5.5

env:
  - DB=mysql

before_script:
  - git clone git://github.com/YOURLS/YOURLS.git
  - git clone git://github.com/ozh/YOURLS-fr_FR.git YOURLS/user/languages/fr
  - cp YOURLS/user/languages/fr/fr_FR.* YOURLS/user/languages
  - mysql -e 'create database IF NOT EXISTS yourls_tests;'
  - cp yourls-tests-config-travis.php YOURLS/user/config.php

script: phpunit --configuration ./phpunit-travis.xml.dist

after_script:

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#YOURLS"
    use_notice: true
