sudo: false
language: php

env:
  global:
  - DB=mysql

services:
  - mysql

matrix:
  include:
  - php: 5.6
  - php: 7.0
  - php: 7.1
  - php: 7.2
  - php: 7.3
  - php: nightly
  - php: hhvm
  fast_finish: true
  allow_failures:
  - php: nightly
  - php: hhvm

before_script:
  - vendor/bin/php-cs-fixer fix --dry-run --format=txt --verbose --diff --diff-format=udiff --config=.cs.php
  - mysql --version
  - git clone git://github.com/YOURLS/YOURLS.git
  - |
    # Use same branch in YOURLS and YOURLS-unit-tests
    export CURRENT_BRANCH=${TRAVIS_PULL_REQUEST_BRANCH:-$TRAVIS_BRANCH}
    echo "Current Tests branch: $CURRENT_BRANCH"
    cd YOURLS
    if [ `git checkout $CURRENT_BRANCH &> /dev/null; echo $?` == 0 ]
    then
      echo "Using branch $CURRENT_BRANCH for YOURLS as well"
    else
      echo "Using branch master for YOURLS"
    fi
    cd ..
  - mysql -e 'create database IF NOT EXISTS yourls_tests;'
  - cp yourls-tests-config-travis.php YOURLS/user/config.php

install: composer install

script:
  - vendor/bin/phpunit --configuration ./phpunit-travis.xml.dist

notifications:
  email: false
